# Generated by Django 3.1.3 on 2020-11-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=25)),
                ('poster', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
    ]
