# Generated by Django 3.1.3 on 2020-11-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_articles_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='price',
        ),
    ]
